### ISSUE TITLE
[Request] Firewall related notice & apply for examption

### ISSUE THREAD

**Issue by slord399** [VRCDN/vrcdn-network-diagnostics#1]
1. As this release be not yet apply to seurity check examption, it blocked by security software and issue following log.
    Please upload exe file to Microsoft and related security authority for examption on security check.
![image](https://github.com/VRCDN/vrcdn-network-diagnostics/assets/50810875/f048cd2d-a0e0-4770-8539-066478f65e56)

2. As it looks, above log not explain anything at all, please consider display pop up to check firewall or security software matter than just close app, it would be more user friendly that way.

**Comment by aaronfrancis635** [comment]
Hey there,

We don't fit the criteria to submit to Microsoft. The app is not detected as PUA or Malware and these are the only options.
![image](https://github.com/VRCDN/vrcdn-network-diagnostics/assets/30204246/9acd57b4-2b8b-4e8f-8dbf-10b2b3265056)

I have however addressed the issue of the error being bland and not warning of potential firewall issues. This change is in the latest release.

**Comment by slord399** [comment]
For Microsoft Smart Screen, they are happy to accept it as "Incorrectly detected as malware/malicious" and put reason as "Unknown Publisher", I do same thing for other app weekly and they removed few hours later without issue.
(no longer detected like this)
![image](https://github.com/VRCDN/vrcdn-network-diagnostics/assets/50810875/77c4079e-cb73-4fe1-aa6a-3d397923af31)

Also, error message seems require some brush up as bit off to say fail in this case.
![image](https://github.com/VRCDN/vrcdn-network-diagnostics/assets/50810875/76cc5330-2ce9-4eaa-ba22-8be3cfca6d26)

**Comment by aaronfrancis635** [comment]
Closing issue from inactivity. 

For the popupt, this is technically a non-issue however removal of the warning is helpful.
Other issues addressed.
